name: Run PHPCS, PHPLint and Cypress

on: [pull_request, pull]

jobs:
  checks:
    strategy:
      matrix:
        tool: ["phpcs", "phplint"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Show tool version info
        run: ./vendor/bin/${{ matrix.tool }} --version

      - name: Run tool
        run: composer ${{ matrix.tool }}
  # Uncomment to enable Cypress check in the future
  # Cypress:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: |
  #           npm run wp-env:config
  #           npm run wp-env start
  #         wait-on: "http://localhost:8888"
  #         browser: chrome
  #         headless: true
